icons = "awesome"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/ryzokuken/mail/igalia/INBOX", "/home/ryzokuken/mail/disroot/INBOX"]

[[block]]
block = "pacman"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = true
use_bits = false

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Default Dark by Chris Kempson (http://chriskempson.com)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#d8d8d8"
info_bg = "#86c1b9"
info_fg = "#181818"
good_bg = "#a1b56c"
good_fg = "#181818"
warning_bg = "#f7ca88"
warning_fg = "#181818"
critical_bg = "#ab4642"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
