# vim:ft=toml

icons = "awesome"

[[block]]
block = "weather"
format = "{weather} {temp}°"
service = { name = "openweathermap", city_id = "1261481", units = "metric" }

[[block]]
block = "pacman"

[[block]]
block = "bluetooth"
mac = "00:16:94:41:63:83"
label = " Sennheiser"

[[block]]
block = "music"
player = "spotify"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "battery"
format = "{percentage}% ({time})"

[[block]]
block = "time"

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Default Dark by Chris Kempson (http://chriskempson.com)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#d8d8d8"
info_bg = "#86c1b9"
info_fg = "#181818"
good_bg = "#a1b56c"
good_fg = "#181818"
warning_bg = "#f7ca88"
warning_fg = "#181818"
critical_bg = "#ab4642"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
